### ISSUE TITLE
How to custom file name?

### ISSUE THREAD

**Issue by buithu** [vishalonlyy/Cloudflare-R2#3]
I want custom file name and remove log.

Please upgrade and give me paypal for me donate.

**Comment by vishalonlyy** [comment]
Hellow thanks for the lookout 
Currently there is no custom feature to actually work with it but yes the feature is scheduled to be released by the end of this March 

For more info please feal free to contact the developers / support personal assistance would surely be given 
https://grootbot.pro/support


- Team
